import {confirm,categories} from './domain.js';
export function seed(){
 const examples=[
 ['Smarter stock planning for a neighborhood shop','Retail','We track stock in spreadsheets and discover empty shelves too late. Weekly ordering takes our manager six hours.','Store manager and purchasing staff','Six months of anonymized sales CSVs and a current product list can be shared.','A simple dashboard that recommends weekly reorder quantities.','Reduce weekly planning from 6 hours to 3 hours in a four-week pilot.','Four-week prototype; use CSV imports and a zero-cost deployment.','Aida at shop@example.com; weekly online review.'],
 ['Help students find the right learning resources','Education','Students struggle to find relevant practice exercises across our scattered course materials.','First-year university students','We can share 120 licensed exercises with topic labels and anonymized feedback.','A searchable prototype that suggests practice by selected topic.','At least 8 out of 10 pilot students find a relevant exercise within 2 minutes.','Deliver a browser prototype in three weeks without collecting student identities.','Dana at learn@example.com; asynchronous feedback and weekly calls.'],
 ['Make local deliveries easier to plan','Logistics','Dispatchers manually group delivery stops every morning, causing long planning sessions.','Two dispatchers at our local delivery business','An anonymized sample of 200 stops and delivery windows is available.','A map-based planning prototype using sample delivery stops.','Cut sample route planning time by 30 percent in 5 dispatcher trials.','Three weeks; do not use live customer addresses in the public demo.','Arman at routes@example.com; two review sessions per week.'],
 ['Understand what café guests tell us','Hospitality','Guest feedback arrives on paper and online, and the café cannot easily see repeated concerns.','Café owner and shift supervisors','We have 80 anonymized feedback notes that can be shared as text.','A prototype that groups feedback into themes for a weekly review.','Correctly categorize at least 80 percent of 50 labeled test comments.','Two-week demo, English text only, no paid services.','Mira at cafe@example.com; weekly online feedback.'],
 ['Turn community event ideas into a plan','Community','Our volunteer group has many event ideas but needs help deciding which ones to try first.','Volunteer coordinators and neighborhood residents','No existing dataset is available; we can provide five organizer interviews.','A simple tool for comparing event ideas against agreed criteria.','Five organizers can rank 10 ideas and explain their top choice.','Prototype in two weeks; mobile friendly and no accounts required.','Samat at community@example.com; weekend review calls.']];
 const make=(row,i,published)=>{const [title,topic,context,users,data,outcome,criteria,constraints,contact]=row;let t={id:`${published?'task':'draft'}-${i+1}`,title,topic,context,users,data,outcome,criteria,constraints,contact,status:published?'published':'draft',createdAt:new Date(Date.now()-i*3600000).toISOString(),confirmed:{},reviewed:false};const keep=published?[7,6,5,3,1][i]:[0,1,2,4,5][i];categories.forEach((c,j)=>{if(j>=keep)t[c.key]='';});return published?confirm(t):t;};
 const teams=[['Steppe AI','Retail, Logistics','Data analysis, UX research','Python, pandas, React'],['Qadam Labs','Education, Community','Product design, frontend','JavaScript, Figma, HTML'],['Nomad Builders','Logistics, Retail','Optimization, backend','Python, FastAPI, SQL'],['Campus Collective','Hospitality, Education','Research, NLP','Python, scikit-learn, Vue'],['Turan Tech','Community, Retail','Full-stack development, testing','TypeScript, Node.js, SQLite']].map((r,i)=>({id:`team-${i+1}`,name:r[0],interests:r[1],skills:r[2],technologies:r[3]}));
 const proposals=teams.map((t,i)=>({id:`proposal-${i+1}`,taskId:`task-${i<3?1:i-1}`,teamId:t.id,idea:`${t.name} will build a focused prototype around the supplied sample data and business workflow.`,plan:'Week 1: validate the problem with the business. Week 2: build and test a prototype. Week 3: evaluate and hand over documentation.',timeline:'3 weeks',prototypeUrl:`https://example.com/demo-${i+1}`,status:'pending',createdAt:new Date().toISOString()}));
 return {tasks:[...examples.map((r,i)=>make(r,i,true)),...examples.map((r,i)=>make(r,i,false))],teams,proposals,milestones:[]};
}
